### ISSUE TITLE
Write SMART objectives of the project

### ISSUE THREAD

**Issue by zestuus** [Programming-Engineering-Pmi-34/Basket-Market#12]
https://docs.google.com/document/d/1ULQU8f40RivKrUQKuddIPBb0tmzsw5FoU_ZBI-l-dYw/edit?usp=sharing

**Comment by zestuus** [comment]
https://docs.google.com/document/d/1ULQU8f40RivKrUQKuddIPBb0tmzsw5FoU_ZBI-l-dYw/edit?usp=sharing

**Comment by ruslan4yk** [comment]
I've checked your task. Good job. I think it's can be moved to Done column.
